language: node_js
node_js: '0.10'

before_install: npm install -g bower

install:
  - npm install
  - bower install

script:
  - ./node_modules/.bin/mocha -c --compilers coffee:coffee-script test
  - npm run-script build
